from tkinter import *
import datetime
from math import *
from tkinter import messagebox
import sys
sys.path.append('c:/users/s-feio/documents')
tkinter = Tk()

text = Text(tkinter, font = ('Helvetica', 30), height = 4, width = 20, bg = '#AFEEEE')
text.grid(row = 0, column = 0, columnspan = 4)
def createbutton(number, name, commandname, gridx, gridy):
    def commandname():
        text.insert(END, number)
    name = Button(tkinter, command = commandname, text = number, width = 8,\
                  height = 1, bg = 'light blue', font = ('Calibri', 25))
    name.grid(row = gridx, column = gridy)
createbutton('0', 'button0', 'command0', 2, 1)
createbutton('1', 'button1', 'command1', 2, 2)
createbutton('2', 'button2', 'command2', 2, 3)

createbutton('3', 'button3', 'command3', 3, 1)
createbutton('4', 'button4', 'command4', 3, 2)
createbutton('5', 'button5', 'command5', 3, 3)

createbutton('6', 'button6', 'command6', 4, 1)
createbutton('7', 'button7', 'command7', 4, 2)
createbutton('8', 'button8', 'command8', 4, 3)

createbutton('9', 'button9', 'command9', 5, 2)

createbutton('+', 'additionbutton', 'additioncommand', 5, 1)
createbutton('-', 'subtractionbutton', 'subtractioncommand', 5, 3)

createbutton('*', 'multiplicationbutton', 'multiplicationcommand', 6, 1)
createbutton('/', 'divisionbutton', 'divisioncommand', 6, 3)
createbutton('(', 'abutton', 'acommand', 9, 1)
createbutton(')', 'bbutton', 'bcommand', 9, 2)
createbutton('.', 'meh', 'aaaargh', 9, 3)

def erase():
    text.delete(1.0, END)

erasebutton = Button(tkinter, font = ('Calibri', 25), command = erase,\
                     text = 'CE', width = 8, height = 1, bg = 'light blue')
erasebutton.grid(row = 10, column = 2)

def equals():
    global evaluate
    try:
        evaluate = eval(text.get("1.0", END))
        text.delete(1.0, END)
        text.insert(END, str(evaluate))
    except:
        text.delete(1.0, END)
        text.insert(END, 'Error')

equalbutton = Button(tkinter, command = equals, font = ('Calibri', 25)\
                     , text = '=', width = 8, height = 1, bg = 'light blue')
equalbutton.grid(row = 6, column = 2, rowspan = 2)
import random
import webbrowser


def membean():
    webbrowser.open('www.membean.com/dashboard')

def discovery():
    webbrowser.open('https://app.discoveryeducation.com/learn/students')

def amplify():
    webbrowser.open('https://my.amplify\
.com/auth/realms/Amplify/protocol/openi\
d-connect/auth?client_id=curriculum&redir\
ect_uri=https%3A%2F%2Fapps.learning.ampli\
fy.com%2Fcurriculum%2F&state=4b95cb7c-3e6\
d-417d-8272-de206e04ff7d&nonce=33fb62ff-f2\
78-4420-aae2-7d66db4e5c2e&response_mode=fragm\
ent&response_type=code&scope=openid')

def gangouts():
    webbrowser.open('www.hangouts.google.com/webchat/start')

def synergy():
    webbrowser.open('https://wa-bsd4\
05-psv.edupoint.com/PXP2_Login_Student.aspx?regenerateSessionId=True')

button = Button(tkinter, text = 'Membean', command = membean, font = ('Calibri', 15),\
                width = 20, height = 2, bg = '#FA8072').grid(row = 2, column = 4)
button2 = Button(tkinter, text = 'Discovery', command = discovery,font = ('Calibri', 15),\
                 width = 20, height = 2, bg = '#FA8072').grid(row = 3, column = 4)
button3 = Button(tkinter, text = 'Amplify', command = amplify, font = ('Calibri', 15),\
                 width = 20, height = 2, bg = '#FA8072').grid(row = 2, column = 5)
button4 = Button(tkinter, text = 'Gangouts', command = gangouts,font = ('Calibri', 15),\
                 width = 20, height = 2, bg = '#FA8072').grid(row = 3, column = 5)
entry = Entry(tkinter, text = 'URL', width = 73, bg = '#FF6961', font = ('Calibri', 13))
entry.grid(row = 4, column = 4, columnspan = 3, sticky = N) 
button5 = Button(tkinter, text = 'Synergy', width = 20, height = 2, font = ('Calibri', 15),\
                 command = synergy, bg = '#FA8072').grid(row = 2, column = 6)

compilation = 'wikipedia'
def website():
    for x in range (1, 10):
        global compilation
        webbrowser.open('www.' + compilation + '.com')
        chars = 'abcdefghijklmnopqrstuvwxyz'
        compilation = ''
        for x in range (1, 4):
            compilation += random.choice(chars)

button6 = Button(tkinter, text = 'Random', width = 20, height = 2,font = ('Calibri', 15),\
                 command = website, bg = '#FA8072').grid(row = 3, column = 6)
def user():
    webbrowser.open(entry.get())

userbutton = Button(tkinter, text = 'Custom', command = user, width = 65, bg = '#FA8072',font = ('Calibri', 15),)\
             .grid(row = 4, column = 4, columnspan = 3, sticky = S)

canvas = Canvas(tkinter, width = 665, height = 190, bg = 'black')
canvas.grid(row = 0, column = 4, columnspan = 3)

text2 = Label(tkinter, bg = '#9BD4F5', font = ('Calibri', 15), width = 43, \
              height = 1, text =  '    Calculator')
text2.grid(row = 1, column = 1, columnspan = 3)
text3 = Label(tkinter, bg = '#B22222', font = ('Calibri', 15), width = 65, \
              height = 1,\
              text = '         Webbrowser')
text3.grid(row = 1, column = 4, columnspan = 3)

sys.path.append('C:\Modules')
import pyautogui, time

text4 = Label(tkinter, bg = '#228B22', font = ('Calibri', 42), width = 23, \
              height = 1,text =  '  AutoClicker')
text4.grid(row = 5, column = 4, columnspan = 3)
pyentry = Entry(tkinter, bg = '#90ee90', width = 15, font = ('Calibri', 20))
pyentry.grid(row = 6, column = 4, sticky = N)
pylabel = Label(tkinter, bg = '#bfff00', font = ('Calibri', 15),\
                text = 'Amount of Times To Click', width = 21, height = 1)
pylabel.grid(row = 6, column = 4, sticky = S)
pyentry1 = Entry(tkinter, bg = '#90ee90', width = 15, font = ('Calibri', 20))
pyentry1.grid(row = 6, column = 5, sticky = N)
pylabel1 = Label(tkinter, bg = '#bfff00', font = ('Calibri', 15),\
                text = 'Time In Between Clicks', width = 21, height = 1)
pylabel1.grid(row = 6, column = 5, sticky = S)
pyentry2 = Entry(tkinter, bg = '#90ee90', width = 15, font = ('Calibri', 20))
pyentry2.grid(row = 6, column = 6, sticky = N)
pylabel2 = Label(tkinter, bg = '#bfff00', font = ('Calibri', 15),\
                text = 'Coordinates (x, y)', width = 21, height = 1)
pylabel2.grid(row = 6, column = 6, sticky = S)

def apply():
    time.sleep(3)
    for a in range (1, int(pyentry.get())):
        exec('pyautogui.click'+str(pyentry2.get()))
        time.sleep(float(pyentry1.get()))

mouseposition = Text(tkinter, font = ('Courier', 35), bg = '#228B22', width = 15, height = 1)
mouseposition.grid(row = 9, column = 4, columnspan = 2)

pybutton = Button(tkinter, bg = '#228B22', font = ('Calibri', 18), width = 17, height = 1\
                  , text = 'Apply', command = apply)
pybutton.grid(row = 9, column = 6)

def createlabel(name, font, text, background, width, height, row, column,\
                sticky, columnspan, rowspan):
    name = Label(tkinter, font = (font), text = text, bg = background\
                 , width = width, height = height)
    name.grid(row = row, column = column)
walklabel = Label(tkinter, font = ('Calibri', 17), text = 'File Walker', \
                  bg = 'brown', width = 25, height = 1)
walklabel.grid(row = 1, column = 7, columnspan = 2)
thing = Label(tkinter, font = ('Segoe UI', 17), text = 'Password Generator', \
              bg = 'yellow', width = 23, height = 1)
thing.grid(row = 0, column = 7, columnspan = 2, sticky = N)
def config(param1, param2):
    param1.delete(1.0, END)
import random
import keyboard, pyautogui
import time
list1 = [
    'people',
    'history',
    'way',
    'art',
    'world',
    'information',
    'map',
    'two',
    'family',
    'government',
    'health',
    'system',
    'computer',
    'meat',
    'year',
    'thanks',
    'music',
    'person',
    'reading',
    'method',
    'data',
    'food',
    'understanding',
    'theory',
    'law',
    'bird',
    'literature',
    'problem',
    'software',
    'control',
    'knowledge',
    'power',
    'ability',
    'economics',
    'love',
    'internet',
    'television',
    'science',
    'library',
    'nature',
    'fact',
    'product',
    'idea',
    'temperature',
    'investment',
    'area',
    'society',
    'activity',
    'story',
    'industry',
    'media',
    'thing',
    'oven',
    'community',
    'definition',
    'safety',
    'quality',
    'development',
    'language',
    'management',
    'player',
    'variety',
    'video',
    'week',
    'security',
    'country',
    'exam',
    'movie',
    'organization',
    'equipment',
    'physics',
    'analysis',
    'policy',
    'series',
    'thought',
    'basis',
    'boyfriend',
    'direction',
    'strategy',
    'technology',
    'army',
    'camera',
    'freedom',
    'paper',
    'environment',
    'child',
    'instance',
    'month',
    'truth',
    'marketing',
    'university',
    'writing',
    'article',
    'department',
    'difference',
    'goal',
    'news',
    'audience',
    'fishing',
    'growth',
    'income',
    'marriage',
    'user',
    'combination',
    'failure',
    'meaning',
    'medicine',
    'philosophy',
    'teacher',
    'communication',
    'night',
    'chemistry',
    'disease',
    'disk',
    'energy',
    'nation',
    'road',
    'role',
    'soup',
    'advertising',
    'location',
    'success',
    'addition',
    'apartment',
    'education',
    'math',
    'moment',
    'painting',
    'politics',
    'attention',
    'decision',
    'event',
    'property',
    'shopping',
    'student',
    'wood',
    'competition',
    'distribution',
    'entertainment',
    'office',
    'population',
    'president',
    'unit',
    'category',
    'cigarette',
    'context',
    'introduction',
    'opportunity',
    'performance',
    'driver',
    'flight',
    'length',
    'magazine',
    'newspaper',
    'relationship',
    'teaching',
    'cell',
    'dealer',
    'debate',
    'finding',
    'lake',
    'member',
    'message',
    'phone',
    'scene',
    'appearance',
    'association',
    'concept',
    'customer',
    'death',
    'discussion',
    'housing',
    'inflation',
    'insurance',
    'mood',
    'woman',
    'advice',
    'blood',
    'effort',
    'expression',
    'importance',
    'opinion',
    'payment',
    'reality',
    'responsibility',
    'situation',
    'skill',
    'statement',
    'wealth',
    'application',
    'city',
    'county',
    'depth',
    'estate',
    'foundation',
    'grandmother',
    'heart',
    'perspective',
    'photo',
    'recipe',
    'studio',
    'topic',
    'collection',
    'depression',
    'imagination',
    'passion',
    'percentage',
    'resource',
    'setting',
    'ad',
    'agency',
    'college',
    'connection',
    'criticism',
    'debt',
    'description',
    'memory',
    'patience',
    'secretary',
    'solution',
    'administration',
    'aspect',
    'attitude',
    'director',
    'personality',
    'psychology',
    'recommendation',
    'response',
    'selection',
    'storage',
    'version',
    'alcohol',
    'argument',
    'complaint',
    'contract',
    'emphasis',
    'highway',
    'loss',
    'membership',
    'possession',
    'preparation',
    'steak',
    'union',
    'agreement',
    'cancer',
    'currency',
    'employment',
    'engineering',
    'entry',
    'interaction',
    'limit',
    'mixture',
    'preference',
    'region',
    'republic',
    'seat',
    'tradition',
    'virus',
    'actor',
    'classroom',
    'delivery',
    'device',
    'difficulty',
    'drama',
    'election',
    'engine',
    'football',
    'guidance',
    'hotel',
    'match',
    'owner',
    'priority',
    'protection',
    'suggestion',
    'tension',
    'variation',
    'anxiety',
    'atmosphere',
    'awareness',
    'bread',
    'climate',
    'comparison',
    'confusion',
    'construction',
    'elevator',
    'emotion',
    'employee',
    'employer',
    'guest',
    'height',
    'leadership',
    'mall',
    'manager',
    'operation',
    'recording',
    'respect',
    'sample',
    'transportation',
    'boring',
    'charity',
    'cousin',
    'disaster',
    'editor',
    'efficiency',
    'excitement',
    'extent',
    'feedback',
    'guitar',
    'homework',
    'leader',
    'mom',
    'outcome',
    'permission',
    'presentation',
    'promotion',
    'reflection',
    'refrigerator',
    'resolution',
    'revenue',
    'session',
    'singer',
    'tennis',
    'basket',
    'bonus',
    'cabinet',
    'childhood',
    'church',
    'clothes',
    'coffee',
    'dinner',
    'drawing',
    'hair',
    'hearing',
    'initiative',
    'judgment',
    'lab',
    'measurement',
    'mode',
    'mud',
    'orange',
    'poetry',
    'police',
    'possibility',
    'procedure',
    'queen',
    'ratio',
    'relation',
    'restaurant',
    'satisfaction',
    'sector',
    'signature',
    'significance',
    'song',
    'tooth',
    'town',
    'vehicle',
    'volume',
    'wife',
    'accident',
    'airport',
    'appointment',
    'arrival',
    'assumption',
    'baseball',
    'chapter',
    'committee',
    'conversation',
    'database',
    'enthusiasm',
    'error',
    'explanation',
    'farmer',
    'gate',
    'girl',
    'hall',
    'historian',
    'hospital',
    'injury',
    'instruction',
    'maintenance',
    'manufacturer',
    'meal',
    'perception',
    'pie',
    'poem',
    'presence',
    'proposal',
    'reception',
    'replacement',
    'revolution',
    'river',
    'son',
    'speech',
    'tea',
    'village',
    'warning',
    'winner',
    'worker',
    'writer',
    'assistance',
    'breath',
    'buyer',
    'chest',
    'chocolate',
    'conclusion',
    'contribution',
    'cookie',
    'courage',
    'dad',
    'desk',
    'drawer',
    'establishment',
    'examination',
    'garbage',
    'grocery',
    'honey',
    'impression',
    'improvement',
    'independence',
    'insect',
    'inspection',
    'inspector',
    'king',
    'ladder',
    'menu',
    'penalty',
    'piano',
    'potato',
    'profession',
    'professor',
    'quantity',
    'reaction',
    'requirement',
    'salad',
    'sister',
    'supermarket',
    'tongue',
    'weakness',
    'wedding',
    'affair',
    'ambition',
    'analyst',
    'apple',
    'assignment',
    'assistant',
    'bathroom',
    'bedroom',
    'beer',
    'birthday',
    'celebration',
    'championship',
    'cheek',
    'client',
    'consequence',
    'departure',
    'diamond',
    'dirt',
    'ear',
    'fortune',
    'friendship',
    'funeral',
    'gene',
    'girlfriend',
    'hat',
    'indication',
    'intention',
    'lady',
    'midnight',
    'negotiation',
    'obligation',
    'passenger',
    'pizza',
    'platform',
    'poet',
    'pollution',
    'recognition',
    'reputation',
    'shirt',
    'sir',
    'speaker',
    'stranger',
    'surgery',
    'sympathy',
    'tale',
    'throat',
    'trainer',
    'uncle',
    'youth',
    'time',
    'work',
    'film',
    'water',
    'money',
    'example',
    'while',
    'business',
    'study',
    'game',
    'life',
    'form',
    'air',
    'day',
    'place',
    'number',
    'part',
    'field',
    'fish',
    'back',
    'process',
    'heat',
    'hand',
    'experience',
    'job',
    'book',
    'end',
    'point',
    'type',
    'home',
    'economy',
    'value',
    'body',
    'market',
    'guide',
    'interest',
    'state',
    'radio',
    'course',
    'company',
    'price',
    'size',
    'card',
    'list',
    'mind',
    'trade',
    'line',
    'care',
    'group',
    'risk',
    'word',
    'fat',
    'force',
    'key',
    'light',
    'training',
    'name',
    'school',
    'top',
    'amount',
    'level',
    'order',
    'practice',
    'research',
    'sense',
    'service',
    'piece',
    'web',
    'boss',
    'sport',
    'fun',
    'house',
    'page',
    'term',
    'test',
    'answer',
    'sound',
    'focus',
    'matter',
    'kind',
    'soil',
    'board',
    'oil',
    'picture',
    'access',
    'garden',
    'range',
    'rate',
    'reason',
    'future',
    'site',
    'demand',
    'exercise',
    'image',
    'case',
    'cause',
    'coast',
    'action',
    'age',
    'bad',
    'boat',
    'record',
    'result',
    'section',
    'building',
    'mouse',
    'cash',
    'class',
    'nothing',
    'period',
    'plan',
    'store',
    'tax',
    'side',
    'subject',
    'space',
    'rule',
    'stock',
    'weather',
    'chance',
    'figure',
    'man',
    'model',
    'source',
    'beginning',
    'earth',
    'program',
    'chicken',
    'design',
    'feature',
    'head',
    'material',
    'purpose',
    'question',
    'rock',
    'salt',
    'act',
    'birth',
    'car',
    'dog',
    'object',
    'scale',
    'sun',
    'note',
    'profit',
    'rent',
    'speed',
    'style',
    'war',
    'bank',
    'craft',
    'half',
    'inside',
    'outside',
    'standard',
    'bus',
    'exchange',
    'eye',
    'fire',
    'position',
    'pressure',
    'stress',
    'advantage',
    'benefit',
    'box',
    'frame',
    'issue',
    'step',
    'cycle',
    'face',
    'item',
    'metal',
    'paint',
    'review',
    'room',
    'screen',
    'structure',
    'view',
    'account',
    'ball',
    'discipline',
    'medium',
    'share',
    'balance',
    'bit',
    'black',
    'bottom',
    'choice',
    'gift',
    'impact',
    'machine',
    'shape',
    'tool',
    'wind',
    'address',
    'average',
    'career',
    'culture',
    'morning',
    'pot',
    'sign',
    'table',
    'task',
    'condition',
    'contact',
    'credit',
    'egg',
    'hope',
    'ice',
    'network',
    'north',
    'square',
    'attempt',
    'date',
    'effect',
    'link',
    'post',
    'star',
    'voice',
    'capital',
    'challenge',
    'friend',
    'self',
    'shot',
    'brush',
    'couple',
    'exit',
    'front',
    'function',
    'lack',
    'living',
    'plant',
    'plastic',
    'spot',
    'summer',
    'taste',
    'theme',
    'track',
    'wing',
    'brain',
    'button',
    'click',
    'desire',
    'foot',
    'gas',
    'influence',
    'notice',
    'rain',
    'wall',
    'base',
    'damage',
    'distance',
    'feeling',
    'pair',
    'savings',
    'staff',
    'sugar',
    'target',
    'text',
    'animal',
    'author',
    'budget',
    'discount',
    'file',
    'ground',
    'lesson',
    'minute',
    'officer',
    'phase',
    'reference',
    'register',
    'sky',
    'stage',
    'stick',
    'title',
    'trouble',
    'bowl',
    'bridge',
    'campaign',
    'character',
    'club',
    'edge',
    'evidence',
    'fan',
    'letter',
    'lock',
    'maximum',
    'novel',
    'option',
    'pack',
    'park',
    'plenty',
    'quarter',
    'skin',
    'sort',
    'weight',
    'baby',
    'background',
    'carry',
    'dish',
    'factor',
    'fruit',
    'glass',
    'joint',
    'master',
    'muscle',
    'red',
    'strength',
    'traffic',
    'trip',
    'vegetable',
    'appeal',
    'chart',
    'gear',
    'ideal',
    'kitchen',
    'land',
    'log',
    'mother',
    'net',
    'party',
    'principle',
    'relative',
    'sale',
    'season',
    'signal',
    'spirit',
    'street',
    'tree',
    'wave',
    'belt',
    'bench',
    'commission',
    'copy',
    'drop',
    'minimum',
    'path',
    'progress',
    'project',
    'sea',
    'south',
    'status',
    'stuff',
    'ticket',
    'tour',
    'angle',
    'blue',
    'breakfast',
    'confidence',
    'daughter',
    'degree',
    'doctor',
    'dot',
    'dream',
    'duty',
    'essay',
    'father',
    'fee',
    'finance',
    'hour',
    'juice',
    'luck',
    'milk',
    'mouth',
    'peace',
    'pipe',
    'stable',
    'storm',
    'substance',
    'team',
    'trick',
    'afternoon',
    'bat',
    'beach',
    'blank',
    'catch',
    'chain',
    'consideration',
    'cream',
    'crew',
    'detail',
    'gold',
    'interview',
    'kid',
    'mark',
    'mission',
    'pain',
    'pleasure',
    'score',
    'screw',
    'sex',
    'shop',
    'shower',
    'suit',
    'tone',
    'window',
    'agent',
    'band',
    'bath',
    'block',
    'bone',
    'calendar',
    'candidate',
    'cap',
    'coat',
    'contest',
    'corner',
    'court',
    'cup',
    'district',
    'door',
    'east',
    'finger',
    'garage',
    'guarantee',
    'hole',
    'hook',
    'implement',
    'layer',
    'lecture',
    'lie',
    'manner',
    'meeting',
    'nose',
    'parking',
    'partner',
    'profile',
    'rice',
    'routine',
    'schedule',
    'swimming',
    'telephone',
    'tip',
    'winter',
    'airline',
    'bag',
    'battle',
    'bed',
    'bill',
    'bother',
    'cake',
    'code',
    'curve',
    'designer',
    'dimension',
    'dress',
    'ease',
    'emergency',
    'evening',
    'extension',
    'farm',
    'fight',
    'gap',
    'grade',
    'holiday',
    'horror',
    'horse',
    'host',
    'husband',
    'loan',
    'mistake',
    'mountain',
    'nail',
    'noise',
    'occasion',
    'package',
    'patient',
    'pause',
    'phrase',
    'proof',
    'race',
    'relief',
    'sand',
    'sentence',
    'shoulder',
    'smoke',
    'stomach',
    'string',
    'tourist',
    'towel',
    'vacation',
    'west',
    'wheel',
    'wine',
    'arm',
    'aside',
    'associate',
    'bet',
    'blow',
    'border',
    'branch',
    'breast',
    'brother',
    'buddy',
    'bunch',
    'chip',
    'coach',
    'cross',
    'document',
    'draft',
    'dust',
    'expert',
    'floor',
    'god',
    'golf',
    'habit',
    'iron',
    'judge',
    'knife',
    'landscape',
    'league',
    'mail',
    'mess',
    'native',
    'opening',
    'parent',
    'pattern',
    'pin',
    'pool',
    'pound',
    'request',
    'salary',
    'shame',
    'shelter',
    'shoe',
    'silver',
    'tackle',
    'tank',
    'trust',
    'assist',
    'bake',
    'bar',
    'bell',
    'bike',
    'blame',
    'boy',
    'brick',
    'chair',
    'closet',
    'clue',
    'collar',
    'comment',
    'conference',
    'devil',
    'diet',
    'fear',
    'fuel',
    'glove',
    'jacket',
    'lunch',
    'monitor',
    'mortgage',
    'nurse',
    'pace',
    'panic',
    'peak',
    'plane',
    'reward',
    'row',
    'sandwich',
    'shock',
    'spite',
    'spray',
    'surprise',
    'till',
    'transition',
    'weekend',
    'welcome',
    'yard',
    'alarm',
    'bend',
    'bicycle',
    'bite',
    'blind',
    'bottle',
    'cable',
    'candle',
    'clerk',
    'cloud',
    'concert',
    'counter',
    'flower',
    'grandfather',
    'harm',
    'knee',
    'lawyer',
    'leather',
    'load',
    'mirror',
    'neck',
    'pension',
    'plate',
    'purple',
    'ruin',
    'ship',
    'skirt',
    'slice',
    'snow',
    'specialist',
    'stroke',
    'switch',
    'trash',
    'tune',
    'zone',
    'anger',
    'award',
    'bid',
    'bitter',
    'boot',
    'bug',
    'camp',
    'candy',
    'carpet',
    'cat',
    'champion',
    'channel',
    'clock',
    'comfort',
    'cow',
    'crack',
    'engineer',
    'entrance',
    'fault',
    'grass',
    'guy',
    'hell',
    'highlight',
    'incident',
    'island',
    'joke',
    'jury',
    'leg',
    'lip',
    'mate',
    'motor',
    'nerve',
    'passage',
    'pen',
    'pride',
    'priest',
    'prize',
    'promise',
    'resident',
    'resort',
    'ring',
    'roof',
    'rope',
    'sail',
    'scheme',
    'script',
    'sock',
    'station',
    'toe',
    'tower',
    'truck',
    'witness',
    'a',
    'you',
    'it',
    'can',
    'will',
    'if',
    'one',
    'many',
    'most',
    'other',
    'use',
    'make',
    'good',
    'look',
    'help',
    'go',
    'great',
    'being',
    'few',
    'might',
    'still',
    'public',
    'read',
    'keep',
    'start',
    'give',
    'human',
    'local',
    'general',
    'she',
    'specific',
    'long',
    'play',
    'feel',
    'high',
    'tonight',
    'put',
    'common',
    'set',
    'change',
    'simple',
    'past',
    'big',
    'possible',
    'particular',
    'today',
    'major',
    'personal',
    'current',
    'national',
    'cut',
    'natural',
    'physical',
    'show',
    'try',
    'check',
    'second',
    'call',
    'move',
    'pay',
    'let',
    'increase',
    'single',
    'individual',
    'turn',
    'ask',
    'buy',
    'guard',
    'hold',
    'main',
    'offer',
    'potential',
    'professional',
    'international',
    'travel',
    'cook',
    'alternative',
    'following',
    'special',
    'working',
    'whole',
    'dance',
    'excuse',
    'cold',
    'commercial',
    'low',
    'purchase',
    'deal',
    'primary',
    'worth',
    'fall',
    'necessary',
    'positive',
    'produce',
    'search',
    'present',
    'spend',
    'talk',
    'creative',
    'tell',
    'cost',
    'drive',
    'green',
    'support',
    'glad',
    'remove',
    'return',
    'run',
    'complex',
    'due',
    'effective',
    'middle',
    'regular',
    'reserve',
    'independent',
    'leave',
    'original',
    'reach',
    'rest',
    'serve',
    'watch',
    'beautiful',
    'charge',
    'active',
    'break',
    'negative',
    'safe',
    'stay',
    'visit',
    'visual',
    'affect',
    'cover',
    'report',
    'rise',
    'walk',
    'white',
    'beyond',
    'junior',
    'pick',
    'unique',
    'anything',
    'classic',
    'final',
    'lift',
    'mix',
    'private',
    'stop',
    'teach',
    'western',
    'concern',
    'familiar',
    'fly',
    'official',
    'broad',
    'comfortable',
    'gain',
    'maybe',
    'rich',
    'save',
    'stand',
    'young',
    'heavy',
    'hello',
    'lead',
    'listen',
    'valuable',
    'worry',
    'handle',
    'leading',
    'meet',
    'release',
    'sell',
    'finish',
    'normal',
    'press',
    'ride',
    'secret',
    'spread',
    'spring',
    'tough',
    'wait',
    'brown',
    'deep',
    'display',
    'flow',
    'hit',
    'objective',
    'shoot',
    'touch',
    'cancel',
    'chemical',
    'cry',
    'dump',
    'extreme',
    'push',
    'conflict',
    'eat',
    'fill',
    'formal',
    'jump',
    'kick',
    'opposite',
    'pass',
    'pitch',
    'remote',
    'total',
    'treat',
    'vast',
    'abuse',
    'beat',
    'burn',
    'deposit',
    'print',
    'raise',
    'sleep',
    'somewhere',
    'advance',
    'anywhere',
    'consist',
    'dark',
    'double',
    'draw',
    'equal',
    'fix',
    'hire',
    'internal',
    'join',
    'kill',
    'sensitive',
    'tap',
    'win',
    'attack',
    'claim',
    'constant',
    'drag',
    'drink',
    'guess',
    'minor',
    'pull',
    'raw',
    'soft',
    'solid',
    'wear',
    'weird',
    'wonder',
    'annual',
    'count',
    'dead',
    'doubt',
    'feed',
    'forever',
    'impress',
    'nobody',
    'repeat',
    'round',
    'sing',
    'slide',
    'strip',
    'whereas',
    'wish',
    'combine',
    'command',
    'dig',
    'divide',
    'equivalent',
    'hang',
    'hunt',
    'initial',
    'march',
    'mention',
    'spiritual',
    'survey',
    'tie',
    'adult',
    'brief',
    'crazy',
    'escape',
    'gather',
    'hate',
    'prior',
    'repair',
    'rough',
    'sad',
    'scratch',
    'sick',
    'strike',
    'employ',
    'external',
    'hurt',
    'illegal',
    'laugh',
    'mobile',
    'nasty',
    'ordinary',
    'respond',
    'royal',
    'senior',
    'split',
    'strain',
    'struggle',
    'swim',
    'train',
    'upper',
    'wash',
    'yellow',
    'convert',
    'crash',
    'dependent',
    'fold',
    'funny',
    'grab',
    'hide',
    'miss',
    'permit',
    'quote',
    'recover',
    'resolve',
    'roll',
    'sink',
    'slip',
    'spare',
    'suspect',
    'sweet',
    'swing',
    'twist',
    'upstairs',
    'usual',
    'abroad',
    'brave',
    'calm',
    'concentrate',
    'estimate',
    'grand',
    'male',
    'mine',
    'prompt',
    'quiet',
    'refuse',
    'regret',
    'reveal',
    'rush',
    'shake',
    'shift',
    'shine',
    'steal',
    'suck',
    'surround',
    'anybody',
    'bear',
    'brilliant',
    'dare',
    'dear',
    'delay',
    'drunk',
    'female',
    'hurry',
    'inevitable',
    'invite',
    'kiss',
    'neat',
    'punch',
    'quit',
    'reply',
    'representative',
    'resist',
    'silly',
    'smile',
    'spell',
    'stretch',
    'stupid',
    'tear',
    'temporary',
    'tomorrow',
    'wake',
    'wrap',
    'yesterday',
]
symbols = '@#$'
var = ''
thing = Text(tkinter, font = ('Segoe UI', 30), \
              bg = '#FFD700', width = 3, height = 2)
thing.grid(row = 0, column = 7, columnspan = 2, sticky = EW)
randonm = 0
randomstr = ''
def blah():
    global randonm, var, randomstr
    randonm = random.randint(101, 999)
    while '0' not in list(str(randonm)):
        randonm = random.randint(101, 999)
    randomstr = random.choice(list1)
    while len(list(randomstr)) <= 3 or len(list(randomstr)) > 8:
        randomstr = random.choice(list1)
    var =  (random.choice(symbols)+str(randonm)+\
            randomstr.capitalize())
    thing.delete(1.0, END)
    thing.insert(END, var)
butt = Button(tkinter, font = ('Arial', 15), bg = '#F0E68C', width = 27,\
              height = 1, text = 'Generate', command = blah)
butt.grid(row = 0, column = 7, columnspan = 2, sticky = S)
          
import os
import time
import sys
import shutil

extensions = set({})

walkentry = Entry(tkinter, bg = '#CD853F', font = ('Calibri', 15), width = 20)
walkentry.grid(row = 2, column = 7, sticky = N)

walklabel = Label(tkinter, bg = '#A0522D', font = ('Calibri', 17), width = 16\
                  , text = 'File Path')
walklabel.grid(row = 2, column = 7, sticky = S)


walkentry2 = Entry(tkinter, bg = '#CD853F', font = ('Calibri', 15), width = 9)
walkentry2.grid(row = 2, column = 8, sticky = N)

walklabel2 = Label(tkinter, bg = '#A0522D', font = ('Calibri', 17), width = 7\
                   , text = 'Extension')
walklabel2.grid(row = 2, column = 8, sticky = S)

walktext = Text(tkinter, bg = '#CD853F', font = ('Courier', 10), width = 38, height = 9)
walktext.grid(row = 4, column = 7, columnspan = 2, rowspan = 2)

ending = '' 
def walk():
    global ending
    walklist = []
    try:
        for i in os.listdir(walkentry.get()):
            if walkentry2.get() != '':
                if '.' in i:
                    ending = i[i.index('.'):]
                    walklist.append(i)
                    
                if ending != walkentry2.get() and ending != '':
                    try:
                        walklist.remove(i)
                    except:
                        pass
            else:
                walklist.append(os.listdir(walkentry.get()))
    except:
        walklist.append('Error. Check File Name and Try Again')

    walktext.delete(1.0, END)
    walktext.insert(END, walklist)
    tkinter.update()    
      
walkbutton = Button(tkinter, bg = '#8B4513', font = ('Calibri', 20), width = 22,\
                    text = 'Find Files', command = walk)
walkbutton.grid(row = 3, column = 7, columnspan = 2)
tkinter.title('Functionality Widget')


def aboutCalculator():
    messagebox.showinfo('Calculator Info', '''
How to use Calculator:
Type a function to be evaluated into the text window.
Or press the buttons to write equations.
You can use functions sin, cosin, tan, arcsin, arcosin, and arctan.
The Calculator will return error if an invalid equation is entered.
''')

def webbrowserl():
    messagebox.showinfo('Webbrowser Info', '''
Use the following shortcuts to access some of your frequent websites.
Input a URL into the text box above the 'Custom' button.
Click that button to access your URL.
All of these websites will open in your default browser
''')

def autoclicker():
    messagebox.showinfo('Autoclicker Info', '''
Input the frequency, amount of clicks, and the coordinates.
The coordinates should be formatted in the format (x, y).
The coordinates are displayed in the dark green text box below the entry fields
If you do not want to add coordinates to your clicking, input ().
If you wish to stop the clicking at any time, move your mouse to the top right corner.
The program waits for 3 seconds before starting, to give you time to switch tabs.
''')

def password():
    messagebox.showinfo('Password Generator Info', '''
Click the button to generate a password.
They are all 8 or more characters long, have a capital letter, symbol, number, and other qualifications most websites require.
If you do not like the password, press the button again and generate a new one.
''')
menubar = Menu(tkinter)
helpmenu = Menu(menubar, tearoff = 0)
helpmenu.add_command(label = 'Calculator', command = aboutCalculator)
helpmenu.add_command(label = 'Webbrowser', command = webbrowserl)
helpmenu.add_command(label = 'Autoclicker', command = autoclicker)
helpmenu.add_command(label = 'Password Generator', command = password)
menubar.add_cascade(label='Help', menu=helpmenu)


tkinter.config(menu = menubar)

while True:
    now = datetime.datetime.now().time()
    canvas.delete('all')
    canvas.create_text(335, 70, font = ('Courier', 50), text = now, fill = '#D4AF37')
    canvas.create_text(335, 125, font = ('Courier', 50), text = datetime.datetime.now().date(), fill = '#D4AF37')
    mouseposition.delete(1.0, END)
    mouseposition.insert(END, str(pyautogui.position()[-5:]))
    tkinter.update()






    










